mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

from rest_framework_jwt.views import obtain_jwt_token

from accounts.views import login_view, register_view, logout_view

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    #urls(r'^<link>/$, "<app_name>.views.<function>")
    url(r'^admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r"^login/", login_view, name='login'),
    url(r"^logout/", logout_view, name='logout'),
    url(r"^register/", register_view, name='register'),
    url(r'^', include("posts.urls", namespace='posts')),

    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/users/', include("accounts.api.urls", namespace='users-api')),
    url(r'^api/comments/', include("comments.api.urls", namespace='comments-api')),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/posts/api/urls.py
from django.conf.urls import url

from .views import PostCreateAPIView, PostListAPIView, PostDetailAPIView, PostDeleteAPIView, PostUpdateAPIView


urlpatterns = [
    #url(r'^$', views.index, name="index"),
    url(r'^$', PostListAPIView.as_view(), name="list"),
    url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name="delete"),
]

mysite/posts/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPostFeed


urlpatterns = [
    #url(r'^$', views.index, name="index"),
    url(r'^$', views.post_list, name="list"),
    url(r'^feed/$', LatestPostFeed(), name='post_feed'),
    url(r'^create/$', views.post_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name="delete"),
    url(r'^(?P<slug>[\w-]+)/share/$', views.post_share, name="share"),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name="list_by_tags"),
]

mysite/posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType

from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown
from taggit.managers import TaggableManager

from comments.models import Comment
from .utils import get_read_time

# Create your models here.


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "{slug}/{filename}".format(slug=instance.slug,
                                      filename=filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    # add some comment
    author2 = models.CharField(max_length=120, null=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)  # models.TimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    tags = TaggableManager()

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content

        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        query_set = Comment.objects.filter_by_instance(instance)
        return query_set

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    # "Tesla title 1" -> "tesla-title-1"
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug

    query_set = Post.objects.filter(slug=slug).order_by("-id")
    exists = query_set.exists()

    if exists:
        new_slug = "{title}-{id}".format(title=slug, id=query_set.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time


pre_save.connect(pre_save_post_receiver, sender=Post)

mysite/posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
            "tags",
        ]


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

mysite/posts/api/views.py
from django.db.models import Q
from rest_framework.generics import CreateAPIView, DestroyAPIView, ListAPIView, RetrieveAPIView, \
    RetrieveUpdateAPIView

from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser
from rest_framework.filters import SearchFilter, OrderingFilter

from .permissions import IsOwnerOrReadOnly

from posts.models import Post
from .pagination import PostPageNumberPagination
from .serializers import PostDetailSerializer, PostListSerializer, PostCreateUpdateSerializer


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    permission_classes = [AllowAny]
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly, IsAdminUser]


class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    permission_classes = [AllowAny]
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination

    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.all()
        # Query from search bar
        query = self.request.GET.get("q")
        if query:
            queryset_list = \
                queryset_list.filter(Q(title__icontains=query) |
                                     Q(content__icontains=query) |
                                     Q(user__first_name__icontains=query) |
                                     Q(user__last_name__icontains=query)).distinct()
        return queryset_list

mysite/posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.core.mail import send_mail

from taggit.models import Tag

from comments.models import Comment
from comments.forms import CommentForm
from .forms import PostForm, EmailPostForm
from .models import Post

# Create your views here.


def index(request):
    return HttpResponse("Hello, world. You're at the blog index.")


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None,
                    request.FILES or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Succesfully created")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)

    # comments
    comments = instance.comments

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(user=request.user,
                                                             content_type=content_type,
                                                             object_id=obj_id,
                                                             content=content_data,
                                                             parent=parent_obj)

        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    post_tags_ids = instance.tags.values_list('id', flat=True)
    similar_posts = Post.objects.active().filter(tags__in=post_tags_ids).exclude(slug=instance.slug)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by("-same_tags", '-publish')[:4]

    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "comments": comments,
        "comment_form": form,
        "similar_posts": similar_posts,
    }
    return render(request, "post_detail.html", context)


def post_list(request, tag_slug=None):
    tag = None

    today = timezone.now().date()

    queryset_list = Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            queryset_list = queryset_list.filter(tags__in=[tag])

    # Query from search bar
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(Q(title__icontains=query) |
                                             Q(content__icontains=query) |
                                             Q(user__first_name__icontains=query) |
                                             Q(user__last_name__icontains=query)).distinct()

    # Splits list of posts into pages
    paginator = Paginator(queryset_list, 15)

    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        "title": "Posts list",
        "objects_list": queryset,
        "page_request_var": page_request_var,
        "today": today,
        "tag": tag,
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)

    form = PostForm(request.POST or None,
                    request.FILES or None,
                    instance=instance)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Succesfully created")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")


def post_share(request, slug=None):
    post = get_object_or_404(Post, slug=slug)
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = '{user_name} ({user_email}) zachęca do przeczytania "{post_title}"'.format(
                user_name=cd['name'],
                user_email=cd['email'],
                post_title=post.title)

            message = 'Przeczytaj post "{post_title}" na stronie {post_url}\n\n'.format(
                post_title=post.title,
                post_url=post_url,
            )

            # send_mail(subject, message, 'admin@mysite.com', [cd['to']])
            print("Message send - not realy")
            sent = True
    else:
        form = EmailPostForm()

    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }

    return render(request, "post_share.html", context)

mysite/posts/templates/base.html
{% load staticfiles %}
{% load posts_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <meta charset="UTF-8">
    <title>
        {% block head_title %}
        My Site in Django 1.10
        {% endblock head_title %}
    </title>

    <link rel="stylesheet" href='{% static "css/base.css" %}'/>
    <style>
        {% block style %}

        {% endblock style %}
    </style>

    {% block head_extra %}
    {% endblock head_extra %}
</head>
<body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.8&appId=536010116457309";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    {% include "messages_display.html" %}

    <div class="container">
        <ol class="breadcrumb">
            <li><img src="http://www.carlogos.org/logo/Tesla-logo-2003-2500x2500.png" height="40" width="40"> <a href='{% url "posts:list" %}'>Home</a></li>
            {% block post_detail_link %}
            {% endblock %}

            {% if not request.user.is_authenticated %}
                <li class="pull-right"><a href='{% url "register" %}'>Register</a></li>
                <li class="pull-right"><a href='{% url "login" %}'>Login</a></li>
            {% else %}
                <li class="pull-right"><a href='{% url "logout" %}'>Logout</a></li>
            {% endif %}
        </ol>

        {% block content %}

        {% endblock content %}
    </div>

    <!-- Latest compiled and minified JavaScript -->
    <script
        src="http://code.jquery.com/jquery-1.12.4.js"
        integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous"></script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text()
                var markedContent = marked(content)
                $(this).html(markedContent)
            })
            $(".post-detail-item img").each(function(){
                $(this).addClass("img-responsive");
            })

            // preview-title
            var titleInput = $("#id_title")

            function setTitle(value){
                if (value) {
                    $("#preview-title").text(value);
                }
            }
            setTitle(titleInput.val())

            titleInput.keyup(function(){
                var newTitle = $(this).val()
                setTitle(newTitle)
            })

            // preview-content
            var contentInput = $("#id_content")

            function setContent(value){
                if (value) {
                    $("#preview-content").html(marked(value));
                    $("#preview-content img").each(function(){
                        $(this).addClass("img-responsive")
                    });
                }
            }
            setContent(contentInput.val())

            contentInput.keyup(function(){
                var newContent = $(this).val()
                setContent(newContent)
            })


            $(".comment-reply-btn").click(function(event){
                event.preventDefault();
                $(this).parent().next(".comment-reply").fadeToggle();
            })
        })

    </script>

</body>
</html>

mysite/posts/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}



<title>
{% block head_title %}
        {{ instance.title }} | {{ block.super }}
{% endblock head_title %}
</title>


<style>
{% block style %}

{% endblock style %}
</style>


{% block content %}
<div class="col-sm-10 col-sm-offset-1">
    <hr/>
    <a class="btn" href="{{ original_post }}">Back to post</a>
    <hr/>
    <br/>

        <p>{{ comment.content }}</p>
        <footer>
            by {{ comment.user }} on {{ comment.timestamp }} | {{ comment.timestamp|timesince }} ago |{% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %} {% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}
        </footer>
        <hr/>
        <div>
            {% for child_comment in comment.children %}
                <blockquote>
                    <p>{{ child_comment.content }}</p>
                    <footer>by {{ child_comment.user }} on {{ child_comment.timestamp }} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %}</footer>
                </blockquote>
            {% endfor %}

            {% if request.user.is_authenticated %}
                <form method="post" action=".">
                    {{ form|crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <input type="submit" value="Reply" class="btn btn-default"> {% csrf_token %}
                </form>
            {% else %}
                <p>You must be logged in to comment</p>
            {% endif %}
        </div>
    <hr/>
    <a href="{{ original_post }}">Back to post</a>
    <hr/>
</div>
{% endblock content %}

mysite/posts/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}



<title>
{% block head_title %}
        {{ instance.title }} | {{ block.super }}
{% endblock head_title %}
</title>


<style>
{% block style %}

{% endblock style %}
</style>


{% block content %}
<div class="col-sm-10 col-sm-offset-1">
    <hr/>
    <h1>Confirm delete</h1>
            <form method="post" action=".">
                <p>Are you sure you want to delete:</p>
                <p>"{{ object.content }}"?</p>
                <input type="submit" value="Confirm" class="btn btn-warning">
                <a href="{{ object.get_absolute_url }}" class="btn btn-default">Exit</a>
            </form>
        </div>
    <hr/>
</div>
{% endblock content %}

mysite/posts/templates/latest_posts.html
{% for post in latest_posts %}
    <div class="col-sm-4">
        <div class="thumbnail">
            {% if post.image %}
                <img src="{{ post.image.url }}" class="img-responsive" style="height:100px"/>
            {% endif %}

            <div class="caption post-detail-item">
                <h4>
                    <a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
                </h4>
                {% if post.user.get_full_name %}
                    <p>Author: {{ post.user.get_full_name }}</p>
                {% endif %}

            </div>
        </div>
    </div>
{% endfor %}

mysite/posts/templates/messages_display.html
{% if messages %}
<div>
    <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
</div>
{% endif %}

mysite/posts/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

<title>
{% block head_title %}
        {{ instance.title }} | {{ block.super }}
{% endblock head_title %}
</title>

{% block post_detail_link %}
<li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}

<style>
{% block style %}

{% endblock style %}
</style>


{% block content %}
<div class="col-sm-10 col-sm-offset-1">

    {% if instance.image %}
        <img src="{{ instance.image.url }}" class="img-responsive" />
    {% endif %}

    <h1>
        {{ title }}
        <small>
            {% if instance.draft %}
                <span style="color:red">Draft</span>
            {% endif %}
            {{ instance.publish }}
            <br/>
        </small>
    </h1>

    <p class="tags">
        Tags:
        {% for tag in instance.tags.all %}
            <a href="{% url 'posts:list_by_tags' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>

    {% if instance.read_time %}
        <p>Read time: {% if instance.read_time <= 1 %} < 1 minute {% else %} {{ instance.read_time }} minutes {% endif %}</p>
    {% endif %}
    {% if instance.user.get_full_name %}
        <p>Author: {{ instance.user.get_full_name }}</p>
    {% endif %}

    <div class="row">
        <div class="col-sm-12">
            <div class="post-detail-item">
                {{ instance.get_markdown }}
            </div>
            <hr/>
            <br/>



            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                Facebook
            </a>

            <a href="https://twitter.com/home?status={{ instance.content|truncatechars:50|urlify }}%20{{ request.build_absolute_uri }}">
                Twitter
            </a>

            <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
                Google+
            </a>


            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}/">
                Linkedin
            </a>

            <a href="{% url 'posts:share' instance.slug %}">Email</a>
            <p>
                <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
            </p>



            <div>
                <p class="lead">Comments</p>
                {% if request.user.is_authenticated %}
                    <form method="post" action=".">
                        {{ comment_form|crispy }}
                        <input type="submit" value="Comment" class="btn btn-default"> {% csrf_token %}
                    </form>
                {% else %}
                    <p>You must be logged in to comment</p>
                {% endif %}
                <hr/>
                {% for comment in comments %}
                    <blockquote>
                        <p>{{ comment.content }}</p>
                        <footer>
                            by {{ comment.user }} on {{ comment.timestamp }} | {{ comment.timestamp|timesince }} ago |{% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %}
                            <a class="comment-reply-btn" href="#">Reply</a> | <a class="" href="{{ comment.get_absolute_url }}">Thread</a> | {% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}
                        </footer>

                        <div class="comment-reply">
                            {% for child_comment in comment.children %}
                                <blockquote>
                                    <p>{{ child_comment.content }}</p>
                                    <footer>by {{ child_comment.user }} on {{ child_comment.timestamp }} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</footer>
                                </blockquote>
                            {% endfor %}

                            {% if request.user.is_authenticated %}
                                <form method="post" action=".">
                                    {{ comment_form|crispy }}
                                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                    <input type="submit" value="Reply" class="btn btn-default"> {% csrf_token %}
                                </form>
                            {% else %}
                                <p>You must be logged in to comment</p>
                            {% endif %}
                        </div>
                    </blockquote>
                    <hr/>
                {% empty %}
                    <p>There are no comments yet. Be the first one!</p>
                    <br>
                    <br>
                {% endfor %}
            </div>
            <hr/>
            <!--<p>-->
                <!--<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>-->
            <!--</p>-->


        </div>
        <div class="similar_posts">
            <h3>Similar Posts</h3>
            <div class="row">
            {% for post in similar_posts %}

                    <div class="col-sm-4">
                        <div class="thumbnail">
                            {% if post.image %}
                                <img src="{{ post.image.url }}" class="img-responsive" style="height:100px"/>
                            {% endif %}

                            <div class="caption post-detail-item">
                                <h4>
                                    <a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
                                </h4>
                                {% if post.user.get_full_name %}
                                    <p>Author: {{ post.user.get_full_name }}</p>
                                {% endif %}

                            </div>
                        </div>
                    </div>

            {% empty %}
                <p>There are no similar posts. This is the first one!</p>
            {% endfor %}
             </div>
        </div>
        <br>
    </div>
</div>
{% endblock content %}